development:
  password: shptka_9912a3002fb65b6305aefb1884ffb95e
  theme_id: "147571441963"
  store: smithfield-footwear.myshopify.com
  ignore_files:
    - config/settings_data.json
    - templates/*.json